services:
  db:
    image: postgres:15
    container_name: gfd-postgres
    restart: always
    environment:
      POSTGRES_USER: gestor
      POSTGRES_PASSWORD: "banana@caramelizada"
      POSTGRES_DB: gfd_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gestor -d gfd_db" ]
      interval: 5s
      timeout: 3s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4
    container_name: gfd-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: midinatto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "F1n@nc@s"
    ports:
      - "8080:80"
    depends_on:
      - db
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: gfd-backend
    restart: always
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gfd_db
      SPRING_DATASOURCE_USERNAME: gestor
      SPRING_DATASOURCE_PASSWORD: "banana@caramelizada"
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: gfd-frontend
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - backend
volumes:
  postgres_data:
