server.port=${SERVER_PORT:8081}
spring.application.name=gestorfinanceiro

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/gfd_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gestor}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:banana@caramelizada}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=true
