services:
  db:
    image: postgres:15
    container_name: gfd-postgres
    restart: always
    environment:
      POSTGRES_USER: gestor
      POSTGRES_PASSWORD: "banana@caramelizada"
      POSTGRES_DB: gfd_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: gfd-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: midinatto@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "F1n@nc@s"
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: